### PR TITLE
Fix typo in documentation

### PR DESCRIPTION
**Pull request by giordano**

### CODE REVIEW

**Comment by mileslucas** [comment]
Thanks for the editing 😃

Do you anticipate pushing additional corrections, or is this ready to merge?

**Comment by giordano** [comment]
Good question, I'm marking this as draft until I finish reading the documentation

**Comment by giordano** [comment]
This is now ready for review.  Failure on Windows with Julia nightly is likely unrelated

**Review by mileslucas — APPROVED** [review]

**Comment by mileslucas** [comment]
Thanks again!

**Pull request merged**
